#!/bin/sh

# Run in each component's directory, one by one
#git-pup() { git push; }

# TODO: Get from `date`
CURRENT_YEAR=2020

git log | grep Date: | tail; git grep -Ei '201[456789].*eaton' \
| egrep -v "${CURRENT_YEAR} Eaton" | sed 's,:.*$,,' | sort \
| egrep -v 'doc/mkman' \
| while read F ; do
    sed -e 's,\(201.\) *- *201.\(.*eaton.*\)$,\1 - '"${CURRENT_YEAR}"'\2,gi' \
        -e 's,\(Copyright (C) 201.\)\( Eaton\),\1 - '"${CURRENT_YEAR}"'\2,gi' \
        -i "$F" ; \
done && meld ~/FTY/fty-alert-engine/license.xml license.xml \
&& ( git add -p license.xml ; git add -p ) \
&& git commit -m "Bump copyrights to ${CURRENT_YEAR}" \
&& read -p "Is all ok?" -t 3 LINE && case "$LINE" in Y|yY|yyY) { git-pup& true ; } ;; esac
