#!/bin/sh

# Quick regenerator of zproject templates as used by 42ity ecosystem workflow,
# including removal of CMake recipes we do not use, and starts "git difftool"
# so you can revise the templated changes. The "gsl" tool should be installed.
# By default uses the currently checked-out workspace under FTY dispatcher repo
# and can use another (-d) or even update the system installation (-r vs. -q)
# if your "sudo" setup permits that; and to use the current system installation
# of zproject pass the -d " " option. You can pre-export a ZPROJECT_SRC value
# in your shell profile, to use some custom path or the system installation.
# To update a Jenkinsfile (not overwritten by default) use -J
# To update a .travis.yml (not overwritten by default) use -T
# To update git/IDE/clang configs (not overwritten by default) use -G
# (C) 2015-2018 by Eaton

[ -s project.xml ] || { echo "FATAL: Your current directory must be the root of a component managed by zproject (project.xml not found in `pwd`)" >&2; exit 1; }
export PATH=/usr/local/bin:$PATH

### Note : you can set your default preference in a shell profile
#ZPROJECT_REMAKE=yes
#ZPROJECT_SRC="$HOME/zeromq/zproject"
[ -n "$ZPROJECT_REMAKE" ] || ZPROJECT_REMAKE=no
[ -n "$ZPROJECT_SRC" ] || ZPROJECT_SRC="`dirname $0`/zproject"
while [ $# -gt 0 ]; do
    case "$1" in
        -q) ZPROJECT_REMAKE=no ;;
        -r) ZPROJECT_REMAKE=yes ;;
        -d) ZPROJECT_SRC="$2"; shift ;;
        -J) rm -f Jenkinsfile ;;
        -T) rm -f .travis.yml ;;
        -G) rm -f .gitignore .gitattributes .editorconfig .clang-format ;;
        *) echo "Unknown param: '$1'" >&2 ; exit 1 ;;
    esac
    shift
done

if [ -n "$ZPROJECT_SRC" ] && [ "$ZPROJECT_SRC" != " " ]; then
    if [ ! -d "$ZPROJECT_SRC" ]; then
        echo "FATAL: ZPROJECT_SRC='$ZPROJECT_SRC' was not found. Use an empty argument -d '' to use the system installation" >&2
        exit 1
    fi
    if [ "$ZPROJECT_REMAKE" = yes ]; then
        echo "NOTE: Updating system installation of zproject from custom sources at $ZPROJECT_SRC"
        ( cd "$ZPROJECT_SRC" && make || exit
          sudo make install || exit ) || exit
    else
        echo "NOTE: Using custom sources of zproject from $ZPROJECT_SRC"
        PATH="$ZPROJECT_SRC:$PATH"
        export PATH
    fi
else
    echo "NOTE: Using system installation of zproject"
fi

gsl project.xml || exit
case "`pwd`" in
    */fty-*|*/etn-*|/ipm-*)
        echo "REMOVING CMAKE files from fty-* sources..."
        rm -f CMake* *.cmake || true
        rm -rf builds/cmake || true
        ;;
esac
./autogen.sh && git difftool -y && git status
