= README for FTY

FTY is a "dispatcher" repository which links (as "git submodules") to the
repositories used to build the 42ITy(TM) project. This includes some third
party projects (git HEADs), forks of third-party projects customized for
42ITy(TM) needs, and of course lots of original development.

For a rebuild from scratch (to be automated) you'd need:

* `gsl` and `zproject` (optional -- to refresh project definitions)
* `libzmq`
* `libczmq`
* `malamute`
* `cxxtools`
* `tntdb`
* `fty-proto`
* other `fty-*` components as needed and possibly with dependencies on
  each other as defined in their `profile.xml` manifests for `zproject`
* `fty-core` and `fty-rest` possibly come last

Note that when you initially check out a clone of this repository, you only
get meta-data. To instantiate (or subsequently update) the actual source
code for the components, run `./sync.sh` in this workspace.

Also note that if you clone `FTY`, the checked-out repositories will likely
initially refer to the component repository URLs as an `origin`, while they
are rather `upstream` for our context (and a real `origin` would be your
development fork of each such component repo you collaborate on). In this
case, change to the subdirectory of the component in question and run the
`git remote` commands to rename references, for example:

----
:; GIT_USER=mygitname
:; REPO_NAME=fty-proto
:; ( cd "$REPO_NAME" && \
    git remote -v | egrep -i '^origin.*github.com/(42ity|imatix|zeromq)/' && \
    git remote rename origin upstream && \
    git remote add origin "https://github.com/$GIT_USER/$REPO_NAME" && \
    git pull --all )
----
